# Configuration copied from docs.haskellstack.org
sudo: false
language: generic
# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5dfabef9855765e0c386
    on_success: change
    on_failure: always
    on_start: never

env:
  global:
    - GH_REF: github.com/jtanguy/hmacaroons.git
    - secure: "cpcJvp233pVNy05VeWgzUEw1xYCekk1xT1x2grzhUx8mpCqXZda+Xbu76QCqLSESPgc8Q39m6bR8c+oLkbgRM1U+hR91+2sccKaP9cLTad0yoPRdm6qDB96mzLcEX+yl22GVVzSg20AZx0B9edIT9z7pnEVMJV4iDwhsx/p5Uas="

matrix:
  include:
  - env: RESOLVER=lts-11.17 PUSH_DOCS=true
    compiler: ": #stack 8.2.2"
  - env: RESOLVER=lts-12.0 PUSH_DOCS=false
    compiler: ": #stack 8.4.3"
  - env: RESOLVER=nightly PUSH_DOCS=false
    compiler: ": #stack nightly"
  allow_failures:
    - env: RESOLVER=nightly


before_install:
- unset CC
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build the dependencies
- stack --no-terminal --install-ghc --resolver $RESOLVER test --bench --only-dependencies
#- stack --no-terminal --resolver $RESOLVER install stack-hpc-coveralls

script:
  - stack --no-terminal --resolver $RESOLVER test --coverage
  - stack --no-terminal --resolver $RESOLVER bench
  # - shc hmacaroons test

after_script:
  - if [ true = $PUSH_DOCS ]; then bash ./scripts/pushdoc.sh; fi
# EOF
